### ISSUE TITLE
An offset of the post content

### ISSUE THREAD

**Issue by oshliaer** [SamuelDebruyn/hugo-material-lite#6]
I'm stuck with [the css settings](https://github.com/SamuelDebruyn/hugo-material-lite/blob/master/static/css/styles.css#L99-L102) I've not tested on all device but if I leave this settings then the post content has an offset. I've created a picture to display [this](https://drive.google.com/file/d/0Bztea6vSatozSUJTR2ZoMWpBa28/view?usp=sharing).

If to switch off `:not(:last-child)` it works fine.

``` css
.main-container .mdl-card__supporting-text /*:not(:last-child)*/ {
    box-sizing: border-box;
    min-height: 76px
}
```

Are here any comments of this issue?
